<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Documento sin t&iacute;tulo</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<style type="text/css">
<!--
.Estilo1 {font-family: Arial, Helvetica, sans-serif}
.Estilo2 {font-size: 12px}
.Estilo3 {font-family: Arial, Helvetica, sans-serif; font-size: 12px; }
-->
</style>
</head>

<body>
<table width="860" border="0">
  <tr bgcolor="#E6E6E6">
    <td colspan="2"><div align="center" class="Estilo1"><strong>FACTURACION</strong></div></td>
    <td width="196"><div align="center" class="Estilo1"><strong>ENTRADAS</strong></div></td>
    <td width="174"><div align="center" class="Estilo1"><strong>SALIDAS</strong></div></td>
  </tr>
  <tr>
    <td bgcolor="#F7A4B3"><div align="center" class="Estilo1 Estilo2">DEBE</div></td>
    <td bgcolor="#F7A4B3"><div align="center" class="Estilo3">HABER</div></td>
    <td bgcolor="#FFBC79"><span class="Estilo3">1. INV. INICIAL </span></td>
    <td bgcolor="#F2FACB"><span class="Estilo3">5. VENTAS </span></td>
  </tr>
  <tr>
    <td width="132" bgcolor="#E8DCFC"><span class="Estilo3">1. FACTURA </span></td>
    <td width="132" bgcolor="#E8DCFC"><span class="Estilo3">4. PAGO X CAJA </span></td>
    <td bgcolor="#FFBC79"><span class="Estilo3">2. COMPRAS </span></td>
    <td bgcolor="#F2FACB"><span class="Estilo3">6. N/DEBITO PROVEEDOR</span></td>
  </tr>
  <tr>
    <td bgcolor="#E8DCFC"><span class="Estilo3">2. NOTA DEBITO </span></td>
    <td bgcolor="#E8DCFC"><span class="Estilo3">5 DESC. X LIQUIDACION </span></td>
    <td bgcolor="#FFBC79"><span class="Estilo3">3. N/CREDITO X DEVOLUCION</span></td>
    <td bgcolor="#F2FACB"><span class="Estilo3">7. AJUSTES NEGATIVOS</span></td>
  </tr>
  <tr>
    <td bgcolor="#E8DCFC"><span class="Estilo3">3. NOTA CREDITO </span></td>
    <td bgcolor="#E8DCFC">&nbsp;</td>
    <td bgcolor="#FFBC79"><span class="Estilo3">4. AJUSTES POSITIVOS </span></td>
    <td bgcolor="#F2FACB"><span class="Estilo3">8. LOTE VENCIDO</span></td>
  </tr>
  <tr>
    <td bgcolor="#E8DCFC">&nbsp;</td>
    <td bgcolor="#E8DCFC">&nbsp;</td>
    <td bgcolor="#FFBC79">&nbsp;</td>
    <td bgcolor="#F2FACB"><span class="Estilo3">9. MERMAS Y ROTURAS </span></td>
  </tr>
  <tr>
    <td bgcolor="#E6E6E6"><div align="center"><span class="Estilo1"><strong>TIPOS DE IVA </strong></span></div></td>
    <td bgcolor="#E6E6E6">&nbsp;</td>
    <td colspan="2" bgcolor="#E6E6E6"><div align="center">configurar pagina </div></td>
  </tr>
  <tr>
    <td bgcolor="#E8DCFC"><div align="center">EXTERNOS</div></td>
    <td bgcolor="#E8DCFC"><div align="center">ASOCIADOS</div></td>
    <td colspan="2" bgcolor="#FFBC79"><div align="center">archivo - configurar pagina  </div></td>
  </tr>
  <tr>
    <td bgcolor="#E8DCFC"><span class="Estilo3">1. RESP. INSCRIPTO </span></td>
    <td bgcolor="#E8DCFC"><span class="Estilo3">RESPONSABLE INSCRIPTO. 1 </span></td>
    <td bgcolor="#FFBC79"><div align="center">formato y opciones </div></td>
    <td bgcolor="#F2FACB"><div align="center">margenes encabezados y pie de pagina </div></td>
  </tr>
  <tr>
    <td bgcolor="#E8DCFC"><span class="Estilo3">2. NO EXISTE </span></td>
    <td bgcolor="#E8DCFC"><span class="Estilo3">EXENTO . 4 </span></td>
    <td bgcolor="#FFBC79"><div align="center">seleccionar Horizontal </div></td>
    <td bgcolor="#F2FACB"><div align="center">superior : 20.0 </div></td>
  </tr>
  <tr>
    <td bgcolor="#E8DCFC"><span class="Estilo3">3. MONOTRIBUTO </span></td>
    <td bgcolor="#E8DCFC"><span class="Estilo3">MONOTRIBUTISTA. 3 </span></td>
    <td bgcolor="#FFBC79"><div align="center">encabezos y pies </div></td>
    <td bgcolor="#F2FACB"><div align="center">izquierda: 15.0 </div></td>
  </tr>
  <tr>
    <td bgcolor="#E8DCFC"><span class="Estilo3">4. EXENTO </span></td>
    <td bgcolor="#E8DCFC"><span class="Estilo3">CONS. FINAL. 5 </span></td>
    <td bgcolor="#FFBC79"><div align="center">Seleccionar todo como </div></td>
    <td bgcolor="#F2FACB"><div align="center">inferior: 15.0 </div></td>
  </tr>
  <tr>
    <td bgcolor="#E8DCFC"><span class="Estilo3">5. CONS. FINAL </span></td>
    <td bgcolor="#E8DCFC">&nbsp;</td>
    <td bgcolor="#FFBC79"><div align="center">&quot;Ninguno&quot;</div></td>
    <td bgcolor="#F2FACB"><div align="center">derecha: 12.0 </div></td>
  </tr>
</table>
</body>
</html>
